version: "3.8"
services:
  web:
    image: ${PROJ_NAME}:latest
    container_name: ${PROJ_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/node/app
      - front-volume:/home/node/app/node_modules
    ports:
      - ${DEV_PORT}:4000
      - ${PRD_PORT}:5000
    tty: true
volumes:
  front-volume:
    name: ${PROJ_NAME}-volume
    driver: local
